name: japan2024
# This environment file is used to set up the environment for the Japan 2024 talk.
# It includes essential packages for data analysis and visualization.
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scikit-learn=1.4.2
  - pip
  - pip:
      - git+https://github.com/aleixalcacer/archetypes.git@fair
